### ISSUE TITLE
Adicionar notas metodológicas de Nivel de Risco e Rt

### ISSUE THREAD

**Issue by fernandascovino** [ImpulsoGov/farolcovid#108]
Colocar de forma semelhante à [metodologia do modelo](https://github.com/ImpulsoGov/simulacovid/blob/master/src/model_description.py)

**Nomes dos items no menu lateral:**

- Níveis de Risco (sugestão .py: `risk_description.py`)
- Estimando taxa de contágio - @ap1631 confere esse nome? (sugestão .py: `rt_description.py`)

**Textos**: link do docs no trello! :)

**Comment by ap1631** [comment]
Nomes:
- Níveis de Risco
- Estimando Ritmo de Contágio 

Pra ficar consistente :)

**Comment by fernandascovino** [comment]
closed a long time ago, moved to pages on #114
